.with-bundle: 
  before_script:
    - bundle install --jobs=$(nproc) --retry=3 --path=vendor --quiet

.test:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "trigger" || $CI_PIPELINE_SOURCE == "pipeline"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always

.ci-image:
  image: docker:20.10
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
  services:
    - docker:20.10-dind
  tags:
    - docker # without this we cannot run dind on .com

.delivery-metrics-ops:
  rules:
    - if: '$CI_SERVER_URL != "https://ops.gitlab.net"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "trigger" || $CI_PIPELINE_SOURCE == "pipeline" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$BUILD_DELIVERY_METRICS == "true"'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - metrics/**/*
      when: always
